services:
  - type: web
    name: gestion_etudiants
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: ton_app_key
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: oswald
          property: connectionString

databases:
  - name: oswald
    plan: free
    databaseName: laravel
    user: laravel